// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerGetHelloData, AppControllerGetHelloResponses, AuthControllerLoginData, AuthControllerLoginResponses, AuthControllerLogoutData, AuthControllerLogoutResponses, AuthControllerMeData, AuthControllerMeResponses, AuthControllerRefreshData, AuthControllerRefreshResponses, AuthControllerRegisterData, AuthControllerRegisterResponses, FriendsControllerAcceptRequestData, FriendsControllerAcceptRequestResponses, FriendsControllerGetFriendsData, FriendsControllerGetFriendshipStatusData, FriendsControllerGetFriendshipStatusResponses, FriendsControllerGetFriendsResponses, FriendsControllerGetRequestsReceivedData, FriendsControllerGetRequestsReceivedResponses, FriendsControllerGetRequestsSentData, FriendsControllerGetRequestsSentResponses, FriendsControllerRejectRequestData, FriendsControllerRejectRequestResponses, FriendsControllerSendRequestData, FriendsControllerSendRequestResponses, TodosControllerCreateTodoData, TodosControllerCreateTodoResponses, TodosControllerDeleteTodoData, TodosControllerDeleteTodoResponses, TodosControllerGetTodosData, TodosControllerGetTodosResponses, TodosControllerGetUserTodosData, TodosControllerGetUserTodosResponses, TodosControllerUpdateTodoData, TodosControllerUpdateTodoResponses, UsersControllerGetData, UsersControllerGetResponses, UsersControllerMeData, UsersControllerMeResponses, UsersControllerUpdateData, UsersControllerUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<AppControllerGetHelloData, ThrowOnError>): RequestResult<AppControllerGetHelloResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AppControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>): RequestResult<AuthControllerRegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthControllerRegisterResponses, unknown, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>): RequestResult<AuthControllerLoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<AuthControllerLoginResponses, unknown, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authControllerMe = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerMeData, ThrowOnError>): RequestResult<AuthControllerMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthControllerMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

export const authControllerRefresh = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerRefreshData, ThrowOnError>): RequestResult<AuthControllerRefreshResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthControllerRefreshResponses, unknown, ThrowOnError>({ url: '/auth/refresh', ...options });

export const authControllerLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthControllerLogoutData, ThrowOnError>): RequestResult<AuthControllerLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthControllerLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

export const usersControllerMe = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerMeData, ThrowOnError>): RequestResult<UsersControllerMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<UsersControllerMeResponses, unknown, ThrowOnError>({ url: '/users/me', ...options });

export const usersControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersControllerUpdateData, ThrowOnError>): RequestResult<UsersControllerUpdateResponses, unknown, ThrowOnError> => (options.client ?? client).patch<UsersControllerUpdateResponses, unknown, ThrowOnError>({
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const usersControllerGet = <ThrowOnError extends boolean = false>(options: Options<UsersControllerGetData, ThrowOnError>): RequestResult<UsersControllerGetResponses, unknown, ThrowOnError> => (options.client ?? client).get<UsersControllerGetResponses, unknown, ThrowOnError>({ url: '/users/{username}', ...options });

export const friendsControllerSendRequest = <ThrowOnError extends boolean = false>(options: Options<FriendsControllerSendRequestData, ThrowOnError>): RequestResult<FriendsControllerSendRequestResponses, unknown, ThrowOnError> => (options.client ?? client).post<FriendsControllerSendRequestResponses, unknown, ThrowOnError>({ url: '/friends/requests/{username}', ...options });

export const friendsControllerGetRequestsReceived = <ThrowOnError extends boolean = false>(options?: Options<FriendsControllerGetRequestsReceivedData, ThrowOnError>): RequestResult<FriendsControllerGetRequestsReceivedResponses, unknown, ThrowOnError> => (options?.client ?? client).get<FriendsControllerGetRequestsReceivedResponses, unknown, ThrowOnError>({ url: '/friends/requests/incoming', ...options });

export const friendsControllerGetRequestsSent = <ThrowOnError extends boolean = false>(options?: Options<FriendsControllerGetRequestsSentData, ThrowOnError>): RequestResult<FriendsControllerGetRequestsSentResponses, unknown, ThrowOnError> => (options?.client ?? client).get<FriendsControllerGetRequestsSentResponses, unknown, ThrowOnError>({ url: '/friends/requests/outgoing', ...options });

export const friendsControllerAcceptRequest = <ThrowOnError extends boolean = false>(options: Options<FriendsControllerAcceptRequestData, ThrowOnError>): RequestResult<FriendsControllerAcceptRequestResponses, unknown, ThrowOnError> => (options.client ?? client).post<FriendsControllerAcceptRequestResponses, unknown, ThrowOnError>({ url: '/friends/{id}/accept', ...options });

export const friendsControllerRejectRequest = <ThrowOnError extends boolean = false>(options: Options<FriendsControllerRejectRequestData, ThrowOnError>): RequestResult<FriendsControllerRejectRequestResponses, unknown, ThrowOnError> => (options.client ?? client).post<FriendsControllerRejectRequestResponses, unknown, ThrowOnError>({ url: '/friends/{id}/reject', ...options });

export const friendsControllerGetFriends = <ThrowOnError extends boolean = false>(options?: Options<FriendsControllerGetFriendsData, ThrowOnError>): RequestResult<FriendsControllerGetFriendsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<FriendsControllerGetFriendsResponses, unknown, ThrowOnError>({ url: '/friends', ...options });

export const friendsControllerGetFriendshipStatus = <ThrowOnError extends boolean = false>(options: Options<FriendsControllerGetFriendshipStatusData, ThrowOnError>): RequestResult<FriendsControllerGetFriendshipStatusResponses, unknown, ThrowOnError> => (options.client ?? client).get<FriendsControllerGetFriendshipStatusResponses, unknown, ThrowOnError>({ url: '/friends/status/{username}', ...options });

export const todosControllerGetTodos = <ThrowOnError extends boolean = false>(options?: Options<TodosControllerGetTodosData, ThrowOnError>): RequestResult<TodosControllerGetTodosResponses, unknown, ThrowOnError> => (options?.client ?? client).get<TodosControllerGetTodosResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos',
    ...options
});

export const todosControllerCreateTodo = <ThrowOnError extends boolean = false>(options: Options<TodosControllerCreateTodoData, ThrowOnError>): RequestResult<TodosControllerCreateTodoResponses, unknown, ThrowOnError> => (options.client ?? client).post<TodosControllerCreateTodoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const todosControllerDeleteTodo = <ThrowOnError extends boolean = false>(options: Options<TodosControllerDeleteTodoData, ThrowOnError>): RequestResult<TodosControllerDeleteTodoResponses, unknown, ThrowOnError> => (options.client ?? client).delete<TodosControllerDeleteTodoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos/{id}',
    ...options
});

export const todosControllerUpdateTodo = <ThrowOnError extends boolean = false>(options: Options<TodosControllerUpdateTodoData, ThrowOnError>): RequestResult<TodosControllerUpdateTodoResponses, unknown, ThrowOnError> => (options.client ?? client).patch<TodosControllerUpdateTodoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const todosControllerGetUserTodos = <ThrowOnError extends boolean = false>(options: Options<TodosControllerGetUserTodosData, ThrowOnError>): RequestResult<TodosControllerGetUserTodosResponses, unknown, ThrowOnError> => (options.client ?? client).get<TodosControllerGetUserTodosResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/todos/users/{username}',
    ...options
});
