// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    email: string;
    username: string;
    password: string;
};

export type RegisterResponseDto = {
    id: string;
    email: string;
    username: string;
};

export type LoginDto = {
    login: string;
    password: string;
};

export type LoginResponseDto = {
    accessToken: string;
};

export type MeResponseDto = {
    id: string;
    username: string;
};

export type UserProfileDto = {
    id: string;
    displayName: string;
    username: string;
    bio: string;
    avatarUrl: string;
};

export type UpdateProfileDto = {
    displayName?: string;
    bio?: string;
};

export type FriendshipDto = {
    id: string;
    status: 'PENDING' | 'ACCEPTED';
    sender: {
        username: string;
    };
    receiver: {
        username: string;
    };
    createdAt: string;
};

export type FriendDto = {
    id: string;
    username: string;
    displayName: string;
    avatarUrl: string;
};

export type RelationshipResponseDto = {
    status: 'NONE' | 'SELF' | 'OUTGOING_REQUEST' | 'INCOMING_REQUEST' | 'FRIENDS';
};

export type CreateTodoDto = {
    title: string;
    description?: string;
    visibility?: 'FRIENDS' | 'PUBLIC' | 'PRIVATE';
};

export type TodoResponseDto = {
    id: string;
    title: string;
    description: string;
    completed: boolean;
    visibility: 'FRIENDS' | 'PUBLIC' | 'PRIVATE';
    createdAt: string;
    updatedAt: string;
};

export type UpdateTodoDto = {
    title?: string;
    description?: string;
    visibility?: 'FRIENDS' | 'PUBLIC' | 'PRIVATE';
    completed?: boolean;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: string;
};

export type AppControllerGetHelloResponse = AppControllerGetHelloResponses[keyof AppControllerGetHelloResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    201: RegisterResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    201: LoginResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthControllerMeResponses = {
    200: MeResponseDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    201: LoginResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutResponses = {
    204: void;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type UsersControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerMeResponses = {
    200: UserProfileDto;
};

export type UsersControllerMeResponse = UsersControllerMeResponses[keyof UsersControllerMeResponses];

export type UsersControllerUpdateData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersControllerUpdateResponses = {
    200: UserProfileDto;
};

export type UsersControllerUpdateResponse = UsersControllerUpdateResponses[keyof UsersControllerUpdateResponses];

export type UsersControllerGetData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/users/{username}';
};

export type UsersControllerGetResponses = {
    200: UserProfileDto;
};

export type UsersControllerGetResponse = UsersControllerGetResponses[keyof UsersControllerGetResponses];

export type FriendsControllerSendRequestData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/friends/requests/{username}';
};

export type FriendsControllerSendRequestResponses = {
    201: FriendshipDto;
};

export type FriendsControllerSendRequestResponse = FriendsControllerSendRequestResponses[keyof FriendsControllerSendRequestResponses];

export type FriendsControllerGetRequestsReceivedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/friends/requests/incoming';
};

export type FriendsControllerGetRequestsReceivedResponses = {
    200: Array<FriendshipDto>;
};

export type FriendsControllerGetRequestsReceivedResponse = FriendsControllerGetRequestsReceivedResponses[keyof FriendsControllerGetRequestsReceivedResponses];

export type FriendsControllerGetRequestsSentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/friends/requests/outgoing';
};

export type FriendsControllerGetRequestsSentResponses = {
    200: Array<FriendshipDto>;
};

export type FriendsControllerGetRequestsSentResponse = FriendsControllerGetRequestsSentResponses[keyof FriendsControllerGetRequestsSentResponses];

export type FriendsControllerAcceptRequestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/friends/{id}/accept';
};

export type FriendsControllerAcceptRequestResponses = {
    201: FriendshipDto;
};

export type FriendsControllerAcceptRequestResponse = FriendsControllerAcceptRequestResponses[keyof FriendsControllerAcceptRequestResponses];

export type FriendsControllerRejectRequestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/friends/{id}/reject';
};

export type FriendsControllerRejectRequestResponses = {
    204: void;
};

export type FriendsControllerRejectRequestResponse = FriendsControllerRejectRequestResponses[keyof FriendsControllerRejectRequestResponses];

export type FriendsControllerGetFriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/friends';
};

export type FriendsControllerGetFriendsResponses = {
    200: Array<FriendDto>;
};

export type FriendsControllerGetFriendsResponse = FriendsControllerGetFriendsResponses[keyof FriendsControllerGetFriendsResponses];

export type FriendsControllerGetFriendshipStatusData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/friends/status/{username}';
};

export type FriendsControllerGetFriendshipStatusResponses = {
    200: RelationshipResponseDto;
};

export type FriendsControllerGetFriendshipStatusResponse = FriendsControllerGetFriendshipStatusResponses[keyof FriendsControllerGetFriendshipStatusResponses];

export type TodosControllerGetTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodosControllerGetTodosResponses = {
    200: Array<TodoResponseDto>;
};

export type TodosControllerGetTodosResponse = TodosControllerGetTodosResponses[keyof TodosControllerGetTodosResponses];

export type TodosControllerCreateTodoData = {
    body: CreateTodoDto;
    path?: never;
    query?: never;
    url: '/todos';
};

export type TodosControllerCreateTodoResponses = {
    201: TodoResponseDto;
};

export type TodosControllerCreateTodoResponse = TodosControllerCreateTodoResponses[keyof TodosControllerCreateTodoResponses];

export type TodosControllerDeleteTodoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodosControllerDeleteTodoResponses = {
    204: void;
};

export type TodosControllerDeleteTodoResponse = TodosControllerDeleteTodoResponses[keyof TodosControllerDeleteTodoResponses];

export type TodosControllerUpdateTodoData = {
    body: UpdateTodoDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/todos/{id}';
};

export type TodosControllerUpdateTodoResponses = {
    200: TodoResponseDto;
};

export type TodosControllerUpdateTodoResponse = TodosControllerUpdateTodoResponses[keyof TodosControllerUpdateTodoResponses];

export type TodosControllerGetUserTodosData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/todos/users/{username}';
};

export type TodosControllerGetUserTodosResponses = {
    200: Array<TodoResponseDto>;
};

export type TodosControllerGetUserTodosResponse = TodosControllerGetUserTodosResponses[keyof TodosControllerGetUserTodosResponses];
